"""API routers package."""
from app.routers import (
    routes_agency,
    routes_anomaly,
    routes_auth,
    routes_billing,
    routes_custom_reports,
    routes_enterprise,
    routes_funnel,
    routes_health,
    routes_insights,
    routes_integrations,
    routes_jobs,
    routes_metrics,
    routes_notifications,
    routes_onboarding,
    routes_sample_data,
    routes_saved_views,
    routes_scheduled_reports,
    routes_team,
    routes_websocket,
)

__all__ = [
    "routes_agency",
    "routes_anomaly",
    "routes_auth",
    "routes_billing",
    "routes_custom_reports",
    "routes_enterprise",
    "routes_funnel",
    "routes_health",
    "routes_insights",
    "routes_integrations",
    "routes_jobs",
    "routes_metrics",
    "routes_notifications",
    "routes_onboarding",
    "routes_sample_data",
    "routes_saved_views",
    "routes_scheduled_reports",
    "routes_team",
    "routes_websocket",
]
